### ISSUE TITLE
运行显示成功，实际没有文件转存

### ISSUE THREAD

**Issue by JoeNik** [Cp0204/quark-auto-save#1]
看转存的日志是转存成功的，但是网盘里面没有文件

保存结果 {'status': 200, 'code': 0, 'message': 'ok', 'timestamp': 1709018260, 'data': {'task_id': '0888b7cdfdc04931bdbf9ae5ac4a9f70'}, 'metadata': {'tq_gap': 500}}

**Comment by Cp0204** [comment]
方便贴出你的任务item吗？

**Comment by JoeNik** [comment]
{
      "taskname": "斗破苍穹",
      "shareurl": "https://pan.quark.cn/s/9591465abd88#/list/share/56df6bf6e71d4e6e839f616d563ee0b8-D%20%E6%96%97%E7%A0%B4%E8%8B%8D%E7%A9%B9%E5%B9%B4%E7%95%AA",
      "savepath": "/alist/动漫/斗破苍穹/",
      "pattern": "^.*\\.(mp4|mkv)",
      "replace": "",
      "enddate": "2026-01-30",
      "emby_id": "",
      "ignore_extension": "true",
      "savepath_fid": "f525bcf865e14e4696fc4b2f3c1db6f2"
    }

**Comment by JoeNik** [comment]
我知道了，空间不够的时候，提示成功，但是实际没有转存成功

**Comment by Cp0204** [comment]
> 我知道了，空间不够的时候，提示成功，但是实际没有转存成功

好的，刚刚我测试配置是对的，pattern `.` 转义要多加一个斜杠 `^.*\\.(mp4|mkv)` 。

在脚本中 “转存任务提交成功” 就当成功，还有一个查询 “任务状态” 的接口的（/1/clouddrive/task），没写。

**Comment by JoeNik** [comment]
APP还有个签到领流量的接口可以写吗

**Comment by Cp0204** [comment]
> APP还有个签到领流量的接口可以写吗

APP的登录鉴权不一样，对普通用户来说没那么好抓，不像网页端一个F12就出来了，cookie有效期又长。

我自身是VIP是没有这个入口的😂，得换个号试一下。

**Comment by JoeNik** [comment]
也是，APP不好抓包。
非VIP用户空间太小了

**Comment by Cp0204** [comment]
> APP还有个签到领流量的接口可以写吗

搞定了，你青龙跑的话拉库更新脚本试试。

**Comment by JoeNik** [comment]
可以签到了，很强啊

**Comment by Cp0204** [comment]
https://github.com/Cp0204/quark-auto-save/commit/b6c5e028e4f66626bb7d758bf683ff93f9e79724
