### ISSUE TITLE
没有推送签到成功消息，大佬帮看看啥原因。。。

### ISSUE THREAD

**Issue by drw2005** [Cp0204/quark-auto-save#12]
1、使用青龙配置文件里的PUSH_PLUS_TOKEN（其他脚本能正常接收推送）；
2、按照说明删去了配置文件quark_config.json中的整个 push_config 数组；
3、环境变量里也配置了；
![QQ截图20240428171107](https://github.com/Cp0204/quark-auto-save/assets/33473981/5796469a-f370-4c27-a6dc-8e2623e06ac3)

但是签到成功后，并没有推送消息，大佬给看看是何原因。

**Comment by Cp0204** [comment]
判断不了，补充log和调试信息

**Comment by gujiwuqing** [comment]
<img width="433" alt="image" src="https://github.com/Cp0204/quark-auto-save/assets/44566835/e065e621-796b-4224-913b-aa8d61b864c5">
老哥 我这样子设置server酱的key设置推送，但是也不起作用 请问是为什么呢

**Comment by Cp0204** [comment]
> <img alt="image" width="433" src="https://private-user-images.githubusercontent.com/44566835/326272797-e065e621-796b-4224-913b-aa8d61b864c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzMjIxMzQsIm5iZiI6MTcxNDMyMTgzNCwicGF0aCI6Ii80NDU2NjgzNS8zMjYyNzI3OTctZTA2NWU2MjEtNzk2Yi00MjI0LTkxM2ItYWE4ZDYxYjg2NGM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI4VDE2MzAzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwODdkZTAzY2EzOTBkMGYwMzJlNTJmZjQ3ZDI5NGMyNzdjYWI1ZWVkNTBmYjA0ODdhYmE0Yjg2ZGE4MmMzMGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.M0SL3RnUEDs6PE7akTLCrtg3WOZ7Y4keljItv7mxbUY"> 老哥 我这样子设置server酱的key设置推送，但是也不起作用 请问是为什么呢

谁叫你的key名😂，PUSH_KEY

**Comment by Cp0204** [comment]
通知推送键名配置同青龙，有些渠道需要同时配置几个参数才生效，参考这份示例：

https://github.com/whyour/qinglong/blob/develop/sample/config.sample.sh

**Comment by drw2005** [comment]
> 判断不了，补充log和调试信息；
> 
> ps.每天只会在第一次签到成功时推送，识别下log是今天“签到”还是“已签到”

确实，昨天是在已经签到过后测试的，今天已经收到正常推送了！
