### ISSUE TITLE
为什么不做一个转存成功自动下载的功能捏

### ISSUE THREAD

**Issue by key762** [Cp0204/quark-auto-save#16]
定时转存到后,不是应该直接下载到本地吗 再起一个alist和rclone是否有点舍近求远了

**Comment by Cp0204** [comment]
这实际上是两个问题：

**为什么不做转存成功自动下载？**

我个人不需要下载到本地。本项目只专注实现转存功能，不涉及本地文件操作。

**为什么用 alist rclone（不是项目的使用要求，只是个人这么用，也推荐这么用）**

alist rclone 是作为桥梁让 emby 索引到资源，随播随下。

也就是说，emby 播放的时候，是直接通过网络获取数据的，等于**在线播放**，有两个好处：

1. NAS无需大储存，夸克容量就是NAS媒体库的容量。
2. 追剧、看电影，其实大部分视频只播放一次，不用等待完全下载，转存后刷新媒体库就能看，很轻量。

但这套方案对网络要求比较高，也无法离线使用，各有利弊。

**简单来说，这样就拥有了一个 emby 做前端，夸克做后端储存的在线媒体库。**

**Comment by key762** [comment]
我用alist 挂载夸克 有点问题 内容不同步 不知道是不是token的问题

**Comment by key762** [comment]
我再试试alist挂载,我逆向看了夸克的下载api,下载超过2G,请求就超时了
