### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by boliang-yes** [Cp0204/quark-auto-save#17]
### What happened

新版手动执行视乎出现了问题
![1](https://github.com/Cp0204/quark-auto-save/assets/66565126/b3fbd767-5663-4f18-a5ff-83c2231e183f)
![2](https://github.com/Cp0204/quark-auto-save/assets/66565126/3f8eee80-70d9-4ef2-b2d8-b4d042cc933f)

### Config & Log

TypeError: can only concatenate str (not "int") to str
stderr: [05-25 23:41:44][ERROR] Exception on /run_script_now [GET]
stderr: Traceback (most recent call last):
stderr:   File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
stderr:     response = self.full_dispatch_request()
stderr:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
stderr:   File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
stderr:     rv = self.handle_user_exception(e)
stderr:          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
stderr:   File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
stderr:     rv = self.dispatch_request()
stderr:          ^^^^^^^^^^^^^^^^^^^^^^^
stderr:   File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
stderr:     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
stderr:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
stderr:   File "/app/./app/run.py", line 171, in run_script_now
stderr:     logging.info(f">>> 手动运行任务{task_index+1}")
stderr:                                     ~~~~~~~~~~^~
stderr: TypeError: can only concatenate str (not "int") to str

### Operating environment

Docker

### Environment version

v0.2.9.9

**Comment by Cp0204** [comment]
😂 了解，已识别问题

**Comment by Cp0204** [comment]
v0.2.9.10 已修复
