### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by boliang-yes** [Cp0204/quark-auto-save#18]
### What happened

不知道是不是任务太多第一个任务就报错，然后一报错就全停止了
![Screenshot_2024-05-28-13-26-17-550_com quark browser](https://github.com/Cp0204/quark-auto-save/assets/66565126/20535bc7-e14a-45b1-af9c-33243615960f)
![Screenshot_2024-05-28-13-26-07-506_com quark browser](https://github.com/Cp0204/quark-auto-save/assets/66565126/4f33c322-2793-42e5-b4df-09dd826d1162)

### Config & Log

Traceback (most recent call last):
  File "/app/./quark_auto_save.py", line 898, in 
    main()
  File "/app/./quark_auto_save.py", line 876, in main
    do_save(accounts[0], [tasklist[task_index]])
  File "/app/./quark_auto_save.py", line 814, in do_save
    is_rename = account.do_rename_task(task)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/./quark_auto_save.py", line 632, in do_rename_task
    is_rename_count += self.do_rename_task(
                       ^^^^^^^^^^^^^^^^^^^^
  File "/app/./quark_auto_save.py", line 626, in do_rename_task
    self.savepath_fid[savepath] = self.get_fids([savepath])[0]["fid"]
                                  ~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

### Operating environment

Qinglong

### Environment version

v0.2.9.10

**Comment by Cp0204** [comment]
保存路径 /开头

**Comment by Cp0204** [comment]
Now, paths omitting `/` at the beginning are compatible, https://github.com/Cp0204/quark-auto-save/commit/76da599e0a879c50683f8c9e2677d66ba1bf59f5
