### ISSUE TITLE
[Bug] 能否在报错后增加重试或者跳过，而不是直接退出。

### ISSUE THREAD

**Issue by heshuji** [Cp0204/quark-auto-save#22]
### What happened

这是我的配置.
![image](https://github.com/Cp0204/quark-auto-save/assets/74350755/8eded980-e01b-4839-afbe-fcf6f14694ef)
1. 在子目录我采用了.* 所以可能会一次性更新的文件比较多。发现会经常出现以下报错。
2. 我问了下Chat GPT。他回答我的：
--------
从报错信息中，我们可以看出这个Python脚本在执行过程中遇到了一个`IndexError: list index out of range`错误。这意味着代码尝试访问一个不存在的列表元素。具体来说，问题出现在以下代码行：

```python
self.savepath_fid[savepath] = self.get_fids([savepath])[0]["fid"]
```

问题出现在调用`self.get_fids([savepath])`时，这个方法返回的列表为空，所以尝试访问列表的第一个元素`[0]`时就会引发`IndexError`。

要解决这个问题，我们需要：

1. 调查为什么`self.get_fids([savepath])`返回了一个空列表。
2. 添加适当的错误处理来避免索引超出范围。

### 调查原因

首先，确保`self.get_fids([savepath])`应该返回什么。如果它应该返回包含“fid”的字典列表，我们需要检查：

- `savepath`是否正确。
- `get_fids`方法是否正确执行。
- `get_fids`方法是否有可能返回空列表。

### 添加错误处理

在代码中添加错误处理，可以防止程序因列表索引错误而崩溃。可以在尝试访问列表元素之前检查列表是否为空：

```python
fids = self.get_fids([savepath])
if fids:
    self.savepath_fid[savepath] = fids[0]["fid"]
else:
    # 处理fids为空的情况
    print(f"Error: Failed to get fid for savepath {savepath}")
    # 根据需要采取进一步的处理措施，比如返回错误，重试等
```

### 更改后的代码

下面是包含错误处理的代码段：

```python
def dir_check_and_save(self, task, pwd_id, stoken, pdir_fid):
    # Your existing code
    # ...

    fids = self.get_fids([savepath])
    if fids:
        self.savepath_fid[savepath] = fids[0]["fid"]
    else:
        # 处理fids为空的情况
        print(f"Error: Failed to get fid for savepath {savepath}")
        return None

    # Continue with the rest of the method
    # ...
```

这样可以确保在`get_fids`方法返回空列表时，代码不会崩溃，并且可以根据具体情况进行处理。

### 检查 `get_fids` 方法

此外，你可能需要检查`get_fids`方法的实现，确保它在所有情况下都能正常工作，或者在失败时提供有用的错误信息。这将有助于你理解为什么它会返回空列表并相应地采取措施。
--------
3. 除此之外，当所有任务执行时，当前面的任务报错以后，后面的任务也会被打断。
4. 建议增加重试，后者报错后接着运行。

### Config & Log

获取目录ID：失败, inner error, requestId 976q6x-22baf9a465c101
Traceback (most recent call last):
  File "/app/./quark_auto_save.py", line 898, in 
    main()
  File "/app/./quark_auto_save.py", line 876, in main
    do_save(accounts[0], [tasklist[task_index]])
  File "/app/./quark_auto_save.py", line 813, in do_save
    is_new = account.do_save_task(task)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/./quark_auto_save.py", line 468, in do_save_task
    updated_tree = self.dir_check_and_save(task, pwd_id, stoken, pdir_fid)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/./quark_auto_save.py", line 542, in dir_check_and_save
    subdir_tree = self.dir_check_and_save(
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/./quark_auto_save.py", line 542, in dir_check_and_save
    subdir_tree = self.dir_check_and_save(
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/./quark_auto_save.py", line 542, in dir_check_and_save
    subdir_tree = self.dir_check_and_save(
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  [Previous line repeated 4 more times]
  File "/app/./quark_auto_save.py", line 498, in dir_check_and_save
    self.savepath_fid[savepath] = self.get_fids([savepath])[0]["fid"]
                                  ~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

### Operating environment

Docker

### Environment version

26.1.3

**Comment by heshuji** [comment]
或者能够手动增加一下间隔时间

**Comment by Cp0204** [comment]
忽略错误和增加间隔不能真正解决问题；

你这个问题是获取网盘目录的fid失败，至于为什么会失败，没有样本，无法测试。

**Comment by heshuji** [comment]
好的谢谢哥，我转存的是这个链接：https://pan.quark.cn/s/e58770863f10#/list/share/c769bf340305473ebb4712d9244171e3-01.2025%E8%80%83%E7%A0%94%E5%86%85%E5%AE%B9%E3%80%90%E6%96%B0%E7%89%88%E3%80%91/69937319925543029e2db68187bad0e6-02.%202025%E4%B8%93%E4%B8%9A%E8%AF%BE%E3%80%90%E6%8C%81%E7%BB%AD%E6%9B%B4%E6%96%B0%E3%80%91

**Comment by Cp0204** [comment]
一再强调提供配置🤣 就在刚刚我手打图片中你的链接，随便点个目录测试的情况下，没有测出异常

![image](https://github.com/Cp0204/quark-auto-save/assets/5239753/a47036a0-c2be-4e40-8ee7-5d6392ab612e)

我再试试

**Comment by Cp0204** [comment]
我的账号无法测试，我空间只有6T，我从5T删到2.5T后还是不够存，删无可删了

转存失败：capacity limit[{0}]

**Comment by heshuji** [comment]
将我的quark_config.json 发送到您的邮箱了。太感谢了哥

**Comment by heshuji** [comment]
参照chatgpt 的意见我修改了此处
497行处
`
        # 获取目标目录文件列表
        savepath = re.sub(r"/{2,}", "/", f"/{task['savepath']}{subdir_path}")
        if not self.savepath_fid.get(savepath):
            fids = self.get_fids([savepath])
            if fids:  # Check if the list is not empty
                self.savepath_fid[savepath] = fids[0]["fid"]
            else:
                print(f"Error: Could not find fid for savepath: {savepath}")
                return tree        
`
以上修改治标不治本，只是忽略了这个报错可以继续运行。结果如下
![image](https://github.com/Cp0204/quark-auto-save/assets/74350755/4fd47259-7292-4f8f-9053-ee46caa7e5ed)
我排查了我自己的文件目录和转存链接的文件目录，发现我自己文件目录这里缺少一个文件夹，所以产生了这个报错。
![image](https://github.com/Cp0204/quark-auto-save/assets/74350755/5479a3cf-6646-467c-95d4-72cbaa40ca3c)

**Comment by Cp0204** [comment]
跑了50分钟，一个任务都没跑完，检查了 1135+ 个子文件夹，最后也是在`02.线代`这里出错

反反复复终于定位到问题。这个问题分两部分看：

## 1

我会对这个获取fid失败的错误容错跳过。

## 2

都是在`02.线代`这里出错，我排查了很久🤣，终于发现是你配置勾了`忽略后缀`

程序把去后缀的 `02.线代` 和 `02.高数1-2 极限的概念与性质【学习包】` 都当成 `02` 同一个文件了

我加个文件夹不去后缀比对应该就解决。

## 最后

正如输入框提示，如果确实是嵌套那么多子文件夹的分享，**子文件夹更新慎用 .*** 

因为每次执行都会对子文件夹历遍比对，可能一个任务就会有上千个请求（每个子文件夹*2请求），不管对夸克服务器还是对你服务器来说，**都相当浪费资源，也并且有可能导致账号异常的问题，这也是本项目不推崇的**。

就程序而言，量变引起质变，任务重了对兼容性、性能都是考验，虽然这次问题解决了，但**个人依然非常反对这类任务**。

**Comment by heshuji** [comment]
非常感谢！
