### ISSUE TITLE
作者您好，我基础尚浅，在ql配置时候出现一点问题，看了手册不太理解怎么处理

### ISSUE THREAD

**Issue by corsgoo** [Cp0204/quark-auto-save#23]
### What happened

问题1;拉库运行脚本后，虽然日志显示从仓库下载quark_config.json ，但是却没有结果，并没有下载该模板，运行了三次一样（网络是正常联通的），解决：我是手工创建该文件并从仓库复制模板。
问题2：quark_config.json 里面配置有些疑惑，比如第一段：{
  "cookie": [ //请用手机验证码登录，CK比较完整！
    "Your pan.quark.cn Cookie1, Only this one will do save task.",
    "Your pan.quark.cn Cookie2, Only sign after this."
，从该描述我不知道到底这个ck1，ck2这些应该怎么写。该模板从JS检测里面直接就报错显示格式错误。
问题3：
    "QUARK_SIGN_NOTIFY": true, //是否发送签到成功通知，也可在环境变量中设置，我在环境变量添加了：QUARK_SIGN_NOTIFY，设定值为true，并且添加PUSH_PLUS_TOKEN，值为token，但是运行脚本无反应。

#### Config
```json
{}
```
#### Log
```
text
```

### Operating environment

Qinglong

**Comment by corsgoo** [comment]
补充：刚刚我把全部环境变量关掉又运行一次脚本，成功下载了配置文件，但是在配置里面还是不能正确镜像ck的填写，改了半天都是报错：## 开始执行... 2024-06-18 12:03:42

===============程序开始===============
⏰ 执行时间: 2024-06-18 12:03:43

⚙️ 正从 quark_config.json 文件中读取配置
❌ cookie 未配置

**Comment by Cp0204** [comment]
已修复远程拉配置。

json 是不支持注释的 `//XXX` 都是我为了说明写的注释，要去除。

至于 json 格式怎么写，这部分知识比较基础，请自行学习，在此不多做阐述了。

新手建议直接用 Docker 部署。

**Comment by corsgoo** [comment]
我把模板的ck上面那段文字删掉。然后把那段英文直接替换成ck，成功运行，但是发现一个问题，如果我下面的转存这些都设置过期时间为今天之前（因为目前没有设置需要的转存资源），脚本能运行但是不会推送，（希望签到成功也给一下推送）。只有有转存的任务时才会进行推送。
## 开始执行... 2024-06-18 12:31:45

===============程序开始===============
⏰ 执行时间: 2024-06-18 12:31:46

⚙️ 正从 quark_config.json 文件中读取配置
===============签到任务===============
▶️ 验证第1个账号
👤 账号昵称: 夸客✅
📅 执行签到: 今日已签到+20MB，连签进度(1/7)✅


===============转存任务===============
转存账号: 夸客


===============程序结束===============
😃 运行时长: 0.59s


## 执行结束... 2024-06-18 12:31:46  耗时 1 秒　　　
这就是没有设置转存，就不会进行推送，作者方便优化一下，仅仅签到，签到成功/失败都调用push进行推送吗，这些方便看到状态，谢谢

**Comment by Cp0204** [comment]
每天只首次成功推送 https://github.com/Cp0204/quark-auto-save/issues/12

**Comment by corsgoo** [comment]
> 每天只首次成功推送 #12

这样啊 那我明天看看
