### ISSUE TITLE
自动签到问题

### ISSUE THREAD

**Issue by hxbjavaee** [Cp0204/quark-auto-save#27]
自动签到功能失效，是接口变更还是失效了？

**Comment by Cp0204** [comment]
已失效

**Comment by hxbjavaee** [comment]
有没有解救办法，是官方接口变更，还是直接取消了

**Comment by Cp0204** [comment]
不清楚，有需求自行研究

**Comment by BNDou** [comment]
> 已失效

大佬，可以尝试在cookie中新增移动端的三个参数: `kps` `sign` `vcode`

info接口和sign接口的params中要加入这三个参数，旧版中的cookie可以去除，[我修改的版本](https://github.com/BNDou/Auto_Check_In/blob/main/checkIn_Quark.py)

sign接口具体如下：

```
url = "https://drive-m.quark.cn/1/clouddrive/capacity/growth/sign"
querystring = {
    "pr": "ucpro",
    "fr": "android",
    "kps": self.param.get('kps'),
    "sign": self.param.get('sign'),
    "vcode": self.param.get('vcode')
}
data = {"sign_cyclic": True}
response = requests.post(url=url, json=data, params=querystring).json()
```

**Comment by Cp0204** [comment]
> > 已失效
> 
> 大佬，可以尝试在cookie中新增移动端的三个参数: `kps` `sign` `vcode`
> 
> info接口和sign接口的params中要加入这三个参数，旧版中的cookie可以去除，[我修改的版本](https://github.com/BNDou/Auto_Check_In/blob/main/checkIn_Quark.py)
> 
> sign接口具体如下：
> 
> ```
> url = "https://drive-m.quark.cn/1/clouddrive/capacity/growth/sign"
> querystring = {
>     "pr": "ucpro",
>     "fr": "android",
>     "kps": self.param.get('kps'),
>     "sign": self.param.get('sign'),
>     "vcode": self.param.get('vcode')
> }
> data = {"sign_cyclic": True}
> response = requests.post(url=url, json=data, params=querystring).json()
> ```

好滴，感谢大佬！

我想需要签到的用户另外用你的脚本好了，感觉在这个项目里不好改：
- 一是要移动端参数，增加了抓包的难度。
- 二是签到不是这个项目主要功能，一开始发现改参数PC端Cookie也能用于移动端签到，才顺便加进去的。

**Comment by Cp0204** [comment]
已解决

https://github.com/Cp0204/quark-auto-save/wiki/%E4%BD%BF%E7%94%A8%E6%8A%80%E5%B7%A7%E9%9B%86%E9%94%A6#%E6%AF%8F%E6%97%A5%E7%AD%BE%E5%88%B0%E9%A2%86%E7%A9%BA%E9%97%B4
