### ISSUE TITLE
A：如何下载指定文件夹视频 & B：转存时按顺序逐个保存视频

### ISSUE THREAD

**Issue by Super-Passerby** [Cp0204/quark-auto-save#29]
QA：如何通过正则表达式，下载指定文件夹的视频。
说明：
一些资源的文件结构形式如下：
<img width="402" alt="re" src="https://github.com/user-attachments/assets/018bf72c-4d0f-4c9c-a677-0bba6ee1a148">
随着视频的更新，文件夹的名称会变动。
这些文件夹下视频的名称为01.mkv 02.mkv 无特征供正则表达式识别。
比如我希望下载 ‘/4KHDR60FPS更至06/’ 文件夹下的所有内容
尝试使用在pattern中添加 ^4KHDR_ 以匹配文件夹，但只用正则表达式似乎不能表示一个文件夹下的所有内容。。。

QB：转存时能否按 \d+ 的顺序逐个保存视频。
说明：
目前夸克的转存逻辑是 如果要转存的文件夹大于剩余容量，就会转存失败，在这个工具里也会因为capacity limit而无法转存。
建议是否可以按照视频文件的 \d+ 顺序，逐个保存视频（保存目录下如已有同名文件则跳过），这样配合Rclone，可以实现即使网盘容量不够，也能自动下载完整部剧到本地（前提是剩余容量要大于单集视频的文件大小）。

**Comment by Cp0204** [comment]
### Q1:
```
"update_subdir": "^4K.*"
"pattern": ".*"
```
二者配合使用
如果子文件夹一直改名，quark-auto-save 是无法跟踪的。

### Q2：
目前API的逻辑是批量转存，如果逐个存势必会增加请求数。
例如原本1个请求存10个文件，改变后需要10个请求，并且增加程序的复杂度。 为了个例用户容量不够，而去做这些牺牲，得不偿失。

**Comment by Super-Passerby** [comment]
> ### Q1:
> ```
> "update_subdir": "^4K.*"
> "pattern": ".*"
> ```
> 
> 二者配合使用 如果子文件夹一直改名，quark-auto-save 是无法跟踪的。
> 
> ### Q2：
> 目前API的逻辑是批量转存，如果逐个存必然会增加请求数。 例如原本存10个文件1个请求，改变后需要10个请求，并且增加程序的复杂度。 为了个例用户容量不够，而去做这些牺牲，得不偿失。

"update_subdir": 是不是只能描述一层目录的情况，如果有多层目录试了下好像不行；
举个例子，比如有三层目录的某分享链接文件结构：
```
TV Series
|----- TV Series A (1986)
|      |----- Season 01
|      |      |----- S01E01.mkv
|      |      |----- S01E02.mkv
|      |----- Season 02 
|----- TV Series B (2011)
|      |----- ......
|----- Others.mkv

试了下
"update_subdir":  "TV Series/TV Series A (1986)"
"savepath": "/Media/TV Series A (1986)"
并不能转存 "Season 01 , Season 02" 到网盘
而只会转存 “TV Series/” 下的“Others.mkv”到 “/Media/TV Series A (1986)” 下

**Comment by Cp0204** [comment]
> 试了下
> "update_subdir":  "TV Series/TV Series A (1986)"
> "savepath": "/Media/TV Series A (1986)"
> 并不能转存 "Season 01 , Season 02" 到网盘
> 而只会转存 “TV Series/” 下的“Others.mkv”到 “/Media/TV Series A (1986)” 下


update_subdir 是匹配文件夹名，而不是路径，案例中的情况可能需要这么写 `^TV Series.*|^Season.*`

**Comment by Super-Passerby** [comment]
> 可以考虑下把“逐个转存”变为“划片转存”，比如要转存100个资源，因为容量不足而失败，可以尝试转存第1-50个资源，如果还是容量不足，再继续尝试只转存第1-25个，以此类推，能实现类似效果，还能减少请求。

请问是在递归目录里匹配还是在根目录，试了下 ^TV Series.*|^Season.* 还是不行～
如果 update_subdir 只是匹配文件夹名的话，应该不太好定位路径...

另，针对Q2:
可以考虑下把“逐个转存”变为“划片转存”，比如要转存100个资源，因为容量不足而失败，可以尝试转存第1-50个资源，如果还是容量不足，再继续尝试只转存第1-25个，以此类推，能实现类似效果，还能减少请求。

**Comment by Cp0204** [comment]
> > 可以考虑下把“逐个转存”变为“划片转存”，比如要转存100个资源，因为容量不足而失败，可以尝试转存第1-50个资源，如果还是容量不足，再继续尝试只转存第1-25个，以此类推，能实现类似效果，还能减少请求。
> 
> 请问是在递归目录里匹配还是在根目录，试了下 ^TV Series._|^Season._ 还是不行～ 如果 update_subdir 只是匹配文件夹名的话，应该不太好定位路径...
> 
> 另，针对Q2: 可以考虑下把“逐个转存”变为“划片转存”，比如要转存100个资源，因为容量不足而失败，可以尝试转存第1-50个资源，如果还是容量不足，再继续尝试只转存第1-25个，以此类推，在设定个同一资源允许的最大请求次数。能实现类似效果，还能减少请求。

Q1：根目录

Q2：见 #14 倒数第二段
