### ISSUE TITLE
CK失效，重新获取填入不能

### ISSUE THREAD

**Issue by lisylva-lee** [Cp0204/quark-auto-save#36]
### What happened

![image](https://github.com/user-attachments/assets/5d10c0f9-0313-45f1-a02d-51cf55a3bf72)

#### Config
```json
{}
```
#### Log
```
text
```

### Operating environment

Docker

**Comment by Cp0204** [comment]
手机验证码登录吗？

**Comment by lisylva-lee** [comment]
网页端-手机夸克扫描获取的CK

**Comment by Cp0204** [comment]
> 网页端-手机夸克扫描获取的CK

自己念一遍输入栏上面两句话，不长👀不要浪费别人时间

**Comment by lisylva-lee** [comment]
多谢，主要是你写着最好用验证码登录，之前网页端也可以就忽略了，sorry
