### ISSUE TITLE
请求加入文件筛选功能

### ISSUE THREAD

**Issue by Flyju** [Cp0204/quark-auto-save#48]
大佬，想请求加入按分辨率筛选文件和关键词排除文件的功能，原因是因为订阅的剧集里同一集可能会有多个版本，比如4K，1080P，甚至还有文件名中有“先看”的初版视频，总之就是只转存效果最好的版本。感谢大佬的无私开源，辛苦大佬了！已打赏

**Comment by Flyju** [comment]
https://pan.quark.cn/s/a5d5171f4c9a?pwd=EMmV#/list/share/f16f4de82b5e49b8bee416ab7b20bd53-T%20%E5%90%9ES%E5%99%AC%E6%98%9FKong%E7%A9%BA[%E5%8A%A8%E7%94%BB]%202024
这个是吞噬星空的分享链接，里面同一集可能会有多个分辨率的版本

**Comment by Cp0204** [comment]
如图所示输入：

`^(\d+).*4K.*\.(mp4|mkv)`
`\1.\2`

![image](https://github.com/user-attachments/assets/bf5c3e8a-24b5-4314-93ba-ee6bf8426bd2)


效果：

![image](https://github.com/user-attachments/assets/a76db56d-8739-48ec-ba6a-f90a517673fd)

**Comment by Flyju** [comment]
好的 谢谢 原来使用正则表达式就可以实现 学习了

**Comment by Cp0204** [comment]
使用正则表达式排除关键词的示例：https://github.com/Cp0204/quark-auto-save/pull/63#issuecomment-2776033263

**Comment by wys-wys** [comment]
> > 佬，请问如果别人分享的文件下边还有一级目录的话正则表达式不处理应该怎么解决 ，写完正则之后只处理最上面那层文件夹里边的视频
> 
> 不处理是什么意思，正则本来就不处理目录

我以为它可以自己探测下级目录呢，找到解决方法了，分享链接旁边有个按钮可以打开下级目录再执行一下就可以了，不好意思没仔细看，不能子目录哈哈哈，感谢大佬的解答
