### ISSUE TITLE
[Bug] file not found

### ISSUE THREAD

**Issue by ulovecode** [Cp0204/quark-auto-save#50]
### What happened

调用 share_token 接口的时候报错 file not found

curl --location 'https://drive-h.quark.cn/1/clouddrive/share/sharepage/token?pr=ucpro&fr=pc&uc_param_str=&__dt=279&__t=1735305474947' \
--header 'accept-language: zh-CN,zh;q=0.9,en;q=0.8' \
--header 'content-type: application/json' \
--header 'cookie: ' \
--data '{"pwd_id":"09a68b62cb2d","passcode":""}'

{
    "status": 400,
    "code": 14021,
    "message": "file not found",
    "req_id": "97q4la-24b3a39641bc34",
    "timestamp": 1735306930,
    "metadata": {
        "_t_group": "0:_s_vp:1",
        "_g_group": "3:_s_vtp:1;0:_s_vp:1;4:_s_wl:1;2:_s_bp:1"
    }
}

#### Config
```json
{}
```
#### Log
```
text
```

### Operating environment

Qinglong

**Comment by Cp0204** [comment]
没有问题

![image](https://github.com/user-attachments/assets/81cf491c-a76c-4ecb-abf7-fef0ff9ba383)
![image](https://github.com/user-attachments/assets/10d550c9-4297-46ad-8ef5-d64da3a165be)

**Comment by Cp0204** [comment]
可能是夸克抽风，或风控

**Comment by ulovecode** [comment]
感谢 应该是风控了
