### ISSUE TITLE
优化推送消息

### ISSUE THREAD

**Issue by cbgytech** [Cp0204/quark-auto-save#7]
### What happened

希望推送消息中的分享链接失效、分享取消等转存失败的提示，加粗变红色（或者其他颜色）提示

#### Config
```json
{}
```
#### Log
```
text
```

### Operating environment

Docker

**Comment by Cp0204** [comment]
无法实现，依赖通知渠道特性，每个人用的渠道不一样，有的渠道支持格式、有的不支持，没办法一一适配。😢
